import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider, ThemeConfig } from 'antd';
import type { Metadata } from 'next';

import './globals.css';

const config: ThemeConfig = {
  token: {
    colorPrimary: '#1890ff',
  },
};

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body>
        <AntdRegistry>
          <ConfigProvider
            theme={ config }
          >
            { children }
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
